### ISSUE TITLE
export error

### ISSUE THREAD

**Issue by pcouas** [rverchere/gitlab-migrator#4]
Hello,

After an succesfull export i have trying to reinport it. I have just changed group name g1 to g4 in foldze
python gitlab-import.py --hostname https://gitlab.com --token TOKEN --input folderi2/ --root g2pcs

Import folderi2/ in parent group g2pcs
Parent group g2pcs with id 83864468 found
Importing g4 to folderi2 with parent_id 83864468
Importing Project 'p1' to 'p1' in 'g2pcs/folderi2' (folderi2/_projects)
Importing Project 'p1' to 'p1' in 'g2pcs/folderi2/s1g4' (folderi2/s1g4\_projects)
Traceback (most recent call last):
  File "C:\python\python379\lib\site-packages\gitlab\exceptions.py", line 336, in wrapped_f
    return f(*args, **kwargs)
  File "C:\python\python379\lib\site-packages\gitlab\v4\objects\projects.py", line 904, in import_project
    "/projects/import", post_data=data, files=files, **kwargs
  File "C:\python\python379\lib\site-packages\gitlab\client.py", line 1028, in http_post
    **kwargs,
  File "C:\python\python379\lib\site-packages\gitlab\client.py", line 797, in http_request
    response_body=result.content,
gitlab.exceptions.GitlabHttpError: 404: 404 Namespace Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gitlab-import.py", line 128, in <module>
    import_projects_from_groups(args.root, args.input)
  File "gitlab-import.py", line 53, in import_projects_from_groups
    import_projects(r_group, r_path)
  File "gitlab-import.py", line 23, in import_projects
    output = gl.projects.import_project(file=p_file, name=p_name, path=p_path, namespace=p_namespace)
  File "C:\python\python379\lib\site-packages\gitlab\exceptions.py", line 338, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabImportError: 404: 404 Namespace Not Found

Could you help me
Thanks

**Comment by rverchere** [comment]
Hi,

Sorry to not answer, but I'm not using it anymore, the code is available "as is" without warranties.
